#!/usr/bin/env zsh
. ~/.zshrc

# for ssh
if [ "$SSH_ID_ED25519" != "" ] && [ ! -f "$HOME/.ssh/id_ed25519" ]; then
    mkdir -p $HOME/.ssh
    echo $SSH_ID_ED25519 > $HOME/.ssh/id_ed25519
fi
if [ "$SSH_ID_ED25519_PUB" != "" ] && [ ! -f "$HOME/.ssh/id_ed25519.pub" ]; then
    mkdir -p $HOME/.ssh
    echo $SSH_ID_ED25519_PUB > $HOME/.ssh/id_ed25519.pub
fi

# for git
username=$(git config --list | grep user.name)
useremail=$(git config --list | grep user.email)
if [ "$GIT_GLOBAL_USER_NAME" != "" ] && [ "$username" -eq "" ]; then
    git config --global user.name "$GIT_GLOBAL_USER_NAME"
fi
if [ "$GIT_GLOBAL_USER_EMAIL" != "" ] && [ "$useremail" -eq "" ]; then
    git config --global user.email "$GIT_GLOBAL_USER_EMAIL"
fi

code-server "$@"

