#!/usr/bin/env zsh
. ~/.zshrc

touch $HOME/.codeserverrc
. $HOME/.codeserverrc

if [ "$CODE_SERVER_INITED" != "true" ]; then
    dir=$(cd "$(dirname "$0")"; pwd)
    $dir/init
    echo "export CODE_SERVER_INITED=true" >> $HOME/.codeserverrc
fi

code-server "$@"
