#!/usr/bin/env zsh

set -e

# for ssh
mkdir -p $HOME/.ssh
if [ ! -f "$HOME/.ssh/id_ed25519" ] && [ "$WI_SSH_ID_ED25519" != "" ]; then
  echo $WI_SSH_ID_ED25519 > $HOME/.ssh/id_ed25519
  chmod 600 $HOME/.ssh/id_ed25519
fi
if [ ! -f "$HOME/.ssh/id_ed25519.pub" ] && [ "$WI_SSH_ID_ED25519_PUB" != "" ]; then
  echo $WI_SSH_ID_ED25519_PUB > $HOME/.ssh/id_ed25519.pub
fi

if [ ! -f "$HOME/.ssh/id_rsa" ] && [ "$WI_SSH_ID_RSA" != "" ]; then
  echo $WI_SSH_ID_RSA > $HOME/.ssh/id_rsa
  chmod 600 $HOME/.ssh/id_rsa
fi
if [ ! -f "$HOME/.ssh/id_rsa.pub" ] && [ "$WI_SSH_ID_RSA_PUB" != "" ]; then
  echo $WI_SSH_ID_RSA_PUB > $HOME/.ssh/id_rsa.pub
fi

if [ ! -f "$HOME/.ssh/known_hosts" ] && [ "$WI_SSH_KEYSCAN" != "" ]; then # Host names seperated by comma. eg `github.com,gitee.com`
  for host in $(echo $WI_SSH_KEYSCAN | tr ',' ' ' | tr ' ', '\n'); do
    ssh-keyscan $host >> $HOME/.ssh/known_hosts || true # This line may break if there is network problem. Ignore the error
  done
fi

# for git
if [ ! -f "$HOME/.gitconfig" ] && [ "$WI_GIT_CONFIG" != "" ]; then
  echo $WI_GIT_CONFIG > "$HOME/.gitconfig"
fi

# init
if [ "$WI_INIT_CMD" != "" ]; then
  sh -c "$WI_INIT_CMD"
fi
