#!/usr/bin/env zsh

set -e

# for ssh
if [ "$SSH_ID_ED25519" != "" ] && [ ! -f "$HOME/.ssh/id_ed25519" ]; then
  mkdir -p $HOME/.ssh
  echo $SSH_ID_ED25519 > $HOME/.ssh/id_ed25519
  chmod 600 $HOME/.ssh/id_ed25519
fi
if [ "$SSH_ID_ED25519_PUB" != "" ] && [ ! -f "$HOME/.ssh/id_ed25519.pub" ]; then
  mkdir -p $HOME/.ssh
  echo $SSH_ID_ED25519_PUB > $HOME/.ssh/id_ed25519.pub
fi
if [ "$SSH_KEYSCAN" != "" ] && [ ! -f "$HOME/.ssh/known_hosts" ]; then # Host names seperated by comma. eg `github.com,gitee.com`
  mkdir -p $HOME/.ssh
  echo $SSH_KEYSCAN | tr ',' ' ' | tr ' ', '\n' | xargs -I {} ssh-keyscan {} >> $HOME/.ssh/known_hosts
fi

# for git
if [ ! -f "$HOME/.gitconfig" ]; then
  if [ "$GIT_CONFIG" != "" ]; then
    echo $GIT_CONFIG > "$HOME/.gitconfig"
  fi
fi

# TODO deprecated remove it later
if [ ! -f "$HOME/.gitconfig" ]; then
  if [ "$GIT_GLOBAL_USER_NAME" != "" ]; then
    git config --global user.name "$GIT_GLOBAL_USER_NAME"
  fi
  if [ "$GIT_GLOBAL_USER_EMAIL" != "" ]; then
    git config --global user.email "$GIT_GLOBAL_USER_EMAIL"
  fi
  if [ "$GIT_GLOBAL_URL" != "" ]; then
    array=(${=GIT_GLOBAL_URL}) # string to array. split by whitespace
    for i in $array; do
      inner_str=$(echo $i | tr ',' ' ') # replace comma with whitespace
      inner_array=(${=inner_str}) # string to array. split by whitespace
      git config --global --add "url.${inner_array[1]}.insteadOf" "${inner_array[2]}"
    done
  fi
fi

# init
if [ "$WEB_IDE_INIT_CMD" != "" ]; then
  sh -c "$WEB_IDE_INIT_CMD"
fi
