#!/usr/bin/env zsh

set -e

# for ssh
mkdir -p $HOME/.ssh
if [ ! -f "$HOME/.ssh/id_ed25519" ] && [ "$SSH_ID_ED25519" != "" ]; then
  echo $SSH_ID_ED25519 > $HOME/.ssh/id_ed25519
  chmod 600 $HOME/.ssh/id_ed25519
fi
if [ ! -f "$HOME/.ssh/id_ed25519.pub" ] && [ "$SSH_ID_ED25519_PUB" != "" ]; then
  echo $SSH_ID_ED25519_PUB > $HOME/.ssh/id_ed25519.pub
fi
if [ ! -f "$HOME/.ssh/known_hosts" ] && [ "$SSH_KEYSCAN" != "" ]; then # Host names seperated by comma. eg `github.com,gitee.com`
  echo $SSH_KEYSCAN | tr ',' ' ' | tr ' ', '\n' | xargs -I {} ssh-keyscan {} >> $HOME/.ssh/known_hosts
fi

# for git
if [ ! -f "$HOME/.gitconfig" ] && [ "$GIT_CONFIG_CONTENT" != "" ]; then
  echo $GIT_CONFIG_CONTENT > "$HOME/.gitconfig"
fi

# init
if [ "$WEB_IDE_INIT_CMD" != "" ]; then
  sh -c "$WEB_IDE_INIT_CMD"
fi
