name: Release

on:
  push:
    branches:
      - main
      - prerelease

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    uses: zanminkian/github-actions/.github/workflows/release.yml@main
    secrets:
      TOKENS: ${{ secrets.TOKENS }}
    with:
      assets: "assets"
